# Generated by Django 4.2.1 on 2023-05-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobScrappy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='interval',
            field=models.CharField(choices=[('Daily', 'daily'), ('Weekly', 'weekly'), ('Monthly', 'monthly')], max_length=10),
        ),
    ]
